ALL_VALID: yes

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " UAC "
- User Account Control

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- cisco
- vmware
- paloalto
- netapp
- dell
- fortinet
- veeam

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

